### ISSUE TITLE
Too long password with padding

### ISSUE THREAD

**Issue by atoponce** [makersphereHQ/emoji-passcodes#19]
The scrypt key length is again back to 32-bytes (256-bits), which is unnecessary.  It really doesn't need to be longer than 72-bits (12-bytes). However, the key length should be a multiple a 6-bits to prevent padding at the end of the string with "=". This means the byte count needs to be a multiple of 3 (8_N)/6 = (4_N)/3:
- 12-bytes (72-bits). EG: MSILHE45ePlfrQJq (16-characters)
- 15-bytes (120-bits). EG: LFrCg9ayodpCX4WEGQoM (20-characters)
- 18-bytes (144-bits). EG: biDv42km9p/1YusOxn/ZkF9N (24-characters)

I think the 12-bytes/72-bits/16-characters generated string is more than enough. If you're ultra-paranoid, you could take that up to 15-bytes/120-bytes/20-characters. Going north of that, is only because you can, not because you need to.

**Comment by makersphereLabs** [comment]
Yup, you're right!
Will update the code to `15-bytes/120-bytes/20-characters`. 😁

**Comment by makersphereLabs** [comment]
@atoponce Can you pull #21 and verify that everything is still working?
Btw. have you seen #20?

**Comment by atoponce** [comment]
#21 looks good so far. I commented on #20.
