### ISSUE TITLE
Format application.html

### ISSUE THREAD

**Issue by daknob** [makersphereHQ/emoji-passcodes#2]
Currently in `build/` there's a file called `application.html`. Since this is the main application code, it's recommended to be formatted and indented, so as to make development easier. If you're currently minifying it to save space in the Base64 encoding of `make.sh`, I recommend running it through a minifier in `make.sh`-time.

**Comment by makersphereLabs** [comment]
Great idea! Any recommendations?
Because we need something that supports HTML/CSS and JavaScript, all in one file.
We could break up the code into single `.css, .js, .html` files, minify and then combine them into one `application.html`.
Should be doable with some `cat/echo` magic.

**Comment by makersphereLabs** [comment]
Added as in enhancement with #6. Can we close this issue?

**Comment by daknob** [comment]
I think you can. However you might want to add one more commit that adds indentation in the `app.html` file.

**Comment by makersphereLabs** [comment]
Opened another issue for this! ✌️
