### ISSUE TITLE
Use industry-standard Makefile

### ISSUE THREAD

**Issue by daknob** [makersphereHQ/emoji-passcodes#3]
While `make.sh` may be a quick and easy way to make this file, you should follow the industry-standard practice of using a `Makefile`. 
You can combine this with Issue #2 and have multiple targets and environments, such as:

``` bash
$ make devel # Run, but don't minify .html, have Debug Strings enabled
$ make prod # Run, minify .html, disable Debug Strings
$ make minify # Minify .html and save in new .html file (.min.html)
```

**Comment by makersphereLabs** [comment]
Perfect! Love the idea.
We've added an extra milestone for this.

**Comment by makersphereLabs** [comment]
#6

**Comment by makersphereLabs** [comment]
Also added with #6. Can you verify that?

**Comment by daknob** [comment]
The `Makefile` seems to be there and it has valid targets. If it works for you you can close this issue, yes.

The primary reason it's there is to assist the developer.. :-)
