### ISSUE TITLE
<div> style broken in Firefox

### ISSUE THREAD

**Issue by atoponce** [makersphereHQ/emoji-passcodes#9]
See screenshot:

![firefox](https://cloud.githubusercontent.com/assets/699572/18755672/563bf218-80aa-11e6-8a7a-98fdd464eb27.png)

**Comment by makersphereLabs** [comment]
Oh snap! 😬
@atoponce Which version of Firefox/Windows are you using?

**Comment by atoponce** [comment]
This is Firefox 48 on my Debian workstation.

**Comment by makersphereLabs** [comment]
@atoponce Haha! Looks a lot like Windows. 😉

**Comment by makersphereLabs** [comment]
@atoponce Found a fix! `input { min-width: 1px; }`
👉 http://stackoverflow.com/questions/27424831/firefox-flexbox-overflow
